### ISSUE TITLE
FreeSASA installation difficulties on Ubuntu

### ISSUE THREAD

**Issue by sconstable** [freesasa/freesasa-python#33]
Hello!
When I try to install freesasa on my ubuntu machine via pip, I get a failure:
```
(venv) sconstable@pop-os:~/bitbucket/localdir$ pip install freesasa
Collecting freesasa
  Using cached freesasa-2.2.0.tar.gz (201 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: freesasa
  Building wheel for freesasa (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Define environment variable USE_CYTHON to build from Cython source
      /home/sconstable/local-dev/venv/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      running bdist_wheel
      running build
      running build_ext
      building 'freesasa' extension
      creating build
      creating build/temp.linux-x86_64-3.10
      creating build/temp.linux-x86_64-3.10/lib
      creating build/temp.linux-x86_64-3.10/lib/src
      creating build/temp.linux-x86_64-3.10/src
      x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Ilib/src -I. -I/home/sconstable/local-dev/venv/include -I/usr/include/python3.10 -c lib/src/classifier.c -o build/temp.linux-x86_64-3.10/lib/src/classifier.o -DHAVE_CONFIG_H -std=gnu99
      lib/src/classifier.c:12:10: fatal error: freesasa_internal.h: No such file or directory
         12 | #include "freesasa_internal.h"
            |          ^~~~~~~~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for freesasa
  Running setup.py clean for freesasa
Failed to build freesasa
Installing collected packages: freesasa
  Running setup.py install for freesasa ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for freesasa did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Define environment variable USE_CYTHON to build from Cython source
      /home/sconstable/local-dev/venv/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      running install
      /home/sconstable/local-dev/venv/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      building 'freesasa' extension
      creating build
      creating build/temp.linux-x86_64-3.10
      creating build/temp.linux-x86_64-3.10/lib
      creating build/temp.linux-x86_64-3.10/lib/src
      creating build/temp.linux-x86_64-3.10/src
      x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Ilib/src -I. -I/home/sconstable/local-dev/venv/include -I/usr/include/python3.10 -c lib/src/classifier.c -o build/temp.linux-x86_64-3.10/lib/src/classifier.o -DHAVE_CONFIG_H -std=gnu99
      lib/src/classifier.c:12:10: fatal error: freesasa_internal.h: No such file or directory
         12 | #include "freesasa_internal.h"
            |          ^~~~~~~~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> freesasa

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```
Looking on PyPI, it seems that wheel files are no longer available for Linux in the latest release?  This wouldn't be too big of a problem, except for on Ubuntu 22.04 and earlier (the latest LTS release) there is no freesasa library available through apt so I have no way to install the software out of the box.

At this point I'm looking into building my own custom wheels and hosting them in a private repo, but maybe your team could just upload linux-compatible wheels yourselves?  If not, could you share the scripts that built the older, freesasa 2.1.0 wheels?

**Comment by mittinatten** [comment]
Hi, I just changed the release workflow recently to Github Actions, because what I was using before wasn't free anymore. The first official release with the new system was yesterday, so thanks for reporting this. There are source distributions available so if you install with the env-variable `USE_CYTHON=1` it should hopefully work for now.

I will try to add the wheels later today or during the weekend.

**Comment by mittinatten** [comment]
Ok, turns out it wasn't so complicated so I've fixed it now. The reason it wasn't there is because you can't publish wheels for Linux to PyPi https://stackoverflow.com/questions/59451069/binary-wheel-cant-be-uploaded-on-pypi-using-twine.

But eggs work (that's what we had before). I needed two attempts to get the workflow config to work, but [2.2.0.post2](https://pypi.org/project/freesasa/2.2.0.post2/) has eggs. Can you verify that it works for you?

**Comment by sconstable** [comment]
Hey thanks for getting back to me so quickly!

1. I tried both of the fixes you proposed here (setting `USE_CYTHON=1` and using `freesasa==2.2.0.post2`) both independently and together still do not allow me to install freesasa.
2. I did an uninstall and used `pip install -v freesasa==2.1.0` to discover that despite the presence of the .egg file, pip is actually pulling in the `.tar.gz` file and building from source.
3. Using `pip download` I was able to download and decompress both source packages and then I searched for header files in both of them:
```
(venv) sconstable@pop-os:~/test_freesasa$ find ./freesasa-2.1.0 -name '*.h'
./freesasa-2.1.0/lib/src/lexer.h
./freesasa-2.1.0/lib/src/classifier.h
./freesasa-2.1.0/lib/src/pdb.h
./freesasa-2.1.0/lib/src/freesasa.h
./freesasa-2.1.0/lib/src/parser.h
./freesasa-2.1.0/lib/src/coord.h
./freesasa-2.1.0/lib/src/freesasa_internal.h
./freesasa-2.1.0/lib/src/selection.h
./freesasa-2.1.0/lib/src/nb.h
./freesasa-2.1.0/config.h
(venv) sconstable@pop-os:~/test_freesasa$ find ./freesasa-2.2.0 -name '*.h'
./freesasa-2.2.0/config.h
```
Therefore, I have come to believe that the fundamental problem is not the presence/absence of eggs or use of Cython, but that the 2.2.0 source distribution is missing the requisite header files in order for the compile to complete successfully.

**Comment by mittinatten** [comment]
Ok, seems something has changed with python versions, when I build the source distribution locally (Python 3.8) the header files are included. The publish workflow does not include them (Python 3.10). Rather than try to figure out why, I just added the files explicitly to the manifest.

I spun up a Docker container with ubuntu:latest and managed to install 2.2.0.post3 from there. Can you confirm that it works at your end too? Since the eggs didn't help, and they're kind of deprecated, I removed them from the workflow again.

Thanks again for reporting this so quickly, hopefully not too many people had time to be affected.

**Comment by sconstable** [comment]
confirmed that `2.2.0.post3` builds and installs normally on my Ubuntu 22.04 machine 😊 thanks so much for the quick turnaround on this!
